% Katrina Janeczko

function janeczko_problem1c
%   HW1 question c: altered version of TEMPLE_ABM_MEXICAN_WAVE_ALTERNATIVE
%
%   Model for a mexican wave in a sports stadium, generated by
%   spectators who stand up and sit down to create the wave as
%   an emergent structure. Model: 0=sitting; 1=standing.
%   Update rule: if sitting and left neighbor standing, then
%   stand up; if standing, then sit down.
%
%   This function takes no inputs. It outputs to the command window a row
%   of 0s and 1s representing people sitting or standing, and must be
%   stepped through 80 times.
%
%   01/2016 by Benjamin Seibold, updated 01/2022 by Katrina Janeczko

% Parameters
n = 40; % number of agents

% Initialization
x = double(1:n==round(n/3));% 5 agents are standing up
x(round(n/3):round(n/3)+4) = 1;

% Computation
for j = 1:80 % time loop
    % Plotting
    fprintf('%d',x)
    fprintf('\n')
    % Update rule
    x0 = x; % create a copy of state vector
    xs = x([end 1:end-1]); % right-shifted copy of state vector
    for i = 1:n % loop over elements of state vector x'
        if x0(i)==0&&xs(i)==1 % if 0 & left neighbor 1,
            x(i) = 1; % become 1
        elseif x0(i)==1&&xs(i)==0 % if 1 and left neighbor 0,
            x(i) = 0; % become 0
        end
    end
    pause
end
