% Katrina Janeczko

function janeczko_problem1b
%   HW1 question b: altered version of TEMPLE_ABM_MEXICAN_WAVE
%
%   Model for a mexican wave in a sports stadium, generated by
%   spectators who stand up and sit down to create the wave as
%   an emergent structure. Model: 0=sitting; 1=standing.
%   Update rule: for one wave, if sitting and left neighbor standing, 
%   then stand up; if standing, then sit down. For other wave, if sitting 
%   and right neighbor standing, then stand up; if standing, then sit down.
%
%   This function takes no inputs. It outputs to the command window a row
%   of 0s and 1s representing people sitting or standing, and must be
%   stepped through 80 times.
%
%   01/2016 by Benjamin Seibold, updated 01/2022 by Katrina Janeczko

% Parameters
n = 40; % number of agents

% Initialization; 3 vectors are initialized 
x = double(1:n==round(n/3));
y = x;
z = x|y;
% a single agent is standing up


% Computation
for j = 1:80 % time loop %%this loop will run 80 times
    % Plotting
    fprintf('%d',z)
    fprintf('\n')
    % Update rule
    x = ~x&x([end 1:end-1]); % If 0 & left neighbor 1, become 1; else: 0
    y = ~y&y([2 3:end 1]); % If 0 & right neighbor 1, become 1; else: 0
    z = x|y; % combined behavior of to-right wave and to-left wave
    

    pause
end
