% Katrina Janeczko

function janeczko_problem1d
%   HW1 question d: altered version of TEMPLE_ABM_MEXICAN_WAVE_ALTERNATIVE
%
%   Model for a mexican wave in a sports stadium, generated by
%   spectators who stand up and sit down to create the wave as
%   an emergent structure. Model: 0=sitting; 1=standing.
%   Update rule: if sitting and left neighbor standing, then
%   stand up with odds of 90%; if standing and left neighbor sitting, then 
%   sit down with odds of 90%.
%
%   This function takes no inputs. It outputs to the command window a row
%   of 0s and 1s representing people sitting or standing, and must be
%   stepped through 80 times. The parameter n must be greater than m.
%
%   01/2016 by Benjamin Seibold, updated 01/2022 by Katrina Janeczko

% Parameters
n = 40; % number of agents
m = 5; % agents standing up initially; m<n

% Initialization
x = double(1:n==round(n/3));
x(round(n/3):round(n/3)+(m-1)) = 1; % 5 agents begin standing up

% Computation
for j = 1:120 % time loop
    % Plotting
    fprintf('%d',x)
    fprintf('\n')
    % Update rule
    x0 = x; % create a copy of state vector
    xr1 = x([end 1:end-1]); % once right-shifted copy of state vector

    for i = 1:n % loop over elements of state vector x'
        if x0(i)==0&&xr1(i)==1 % if 0 & immediate left neighbor 1
                x(i) = rand<.90; % 90% chance to become 1
        elseif x0(i)==1&&xr1(i)==0% if 1 and left neighbor 0
            x(i) = rand>.90; % 90% chance to become 0
        end
    end
    pause
end